name: Push to the main repository

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ 8, 11, 14 ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/apache/activemq/artemis-*
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      # use 'install' so smoke-tests will work
      # use '-Pextra-tests' to ensure extra-tests compiles even though they won't actually run
      # By setting anything to org.apache.activemq.artemis.core.io.aio.AIOSequentialFileFactory.DISABLED we are disabling libaio loading on the testsuite
      - name: Build
        run: |
          set -e
          mvn -Dorg.apache.activemq.artemis.core.io.aio.AIOSequentialFileFactory.DISABLED=AnythingNotNull -Djdk8-errorprone -Pfast-tests -Pextra-tests -Ptests-CI -B install -q
          cd examples
          mvn install -PnoRun -B -q

    #  - name: Execute tests
    #  - name: Upload image with tag :dev to image registry
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: username
          password: ${{ secrets.QUAY_PASSWORD }}
          registry: quay.io
          repository: artemiscloud/activemq-artemis
          path: ./artemis-docker/
          dockerfile: Dockerfile-centos
          tags: dev

