name: On published release
on:
  release:
    types: [published]
jobs:
  push_to_registries:
    name: Push image to registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build and push Dockerfile-centos image
        uses: docker/build-push-action@v1
        with:
          username: username
          password: ${{ secrets.QUAY_PASSWORD }}
          registry: quay.io
          repository: artemiscloud/activemq-artemis
          path: ./artemis-docker/
          dockerfile: Dockerfile-centos
          tag_with_ref: true